[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.29"
volatile = "0.6.1"
spin = "0.9.8"
x86_64 = "0.15.1"

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 33
