[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = ".cargo/runners/x86_64-unknown-uefi.sh"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
